### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#140]
**Describe the solution you'd like**
Add the ability to create user account. There should be a sign up button somewhere on the login view.

**Comment by ChFlick** [comment]
I fiddled a little bit with user accounts around and started to work on it a little bit to enable User/Role creation on the database instead of in-memory. No registration but just the backend to enable account storage in the DB. It's based on the MySQL switch in #169.

Maybe it could be a separate issue/PR from the registration.

**Comment by knjk04** [comment]
Sounds good. Could you make a separate issue for that as you know more than I do about this?

**Comment by ChFlick** [comment]
I'd take this issue :)

**Comment by knjk04** [comment]
Thanks a lot!
