### ISSUE TITLE
Add series position

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#17]
**Describe the solution you'd like**
Let a user specify which position the book is in a series. For example, 'Harry Potter and the Prisoner of Azkaban' is the third book in the Harry Potter series.

This would involve adding an `int` field to the `Book` POJO. 

If set, this can be displayed in the title. For example, 

`Harry Potter and the Prisoner of Azkaban (#3)`

Branch off [master](https://github.com/knjk04/book-project).

**Comment by rubenamcruz** [comment]
Hi, do you mind If I work on this issue?

**Comment by knjk04** [comment]
Hi,

Not at all, go ahead. Thanks!

**Comment by rubenamcruz** [comment]
Hi, 
I'm taking a look into this issue, and I'd like to address how I'm thinking about solving it. 
I've added the series variable to the Book and BookForm class, and I created a validation to allow the value to be null, but not negative. If the value is null or 0 it will not be displayed with the Title on the table, otherwise it will be displayed like mentioned on the issue. 
Would you like me to address this in a different way?

**Comment by knjk04** [comment]
No, I think the way you've gone about it is fine.

If you want, you can create a draft PR so I can see what you've done so far.

You said you've added some validation to prevent the series position from being negative -- that's great. Have you also prevented zero from being passed in?

**Comment by rubenamcruz** [comment]
I've allowed zero to being passed as a neutral element, but I can remove it. But should I let the null value being passed? Like I said, if the value is zero or null, I'd take it as a neutral element which would not appear in the list. I will prepare a PR with the changes today

**Comment by knjk04** [comment]
Sorry, I thought I responded to this. I think what you have done is fine. Thanks!

**Comment by rubenamcruz** [comment]
Hi, I'm sorry I'm taking so long, I didn't really have time this last week. Tomorrow I will submit a new PR

**Comment by knjk04** [comment]
No matter :)
