### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#195]
It should be clear that the logo is something book-related. It should be simple. For example, our current banner (see the README) has a book and some text. The new logo could just be an image or some text.

The logo and [favicon](https://github.com/knjk04/book-project/issues/34) should be kept relatively in-sync (use similar colours, for example). Ideally, the favicon would just be a smaller version of the logo.

Formats required: png and possibly a higher quality file format.

**Comment by Onyx-Obelisk** [comment]
This has been my attempt to make a _snazzier_ icon, as you requested in the[ Favicon issue.](url)

![Book_Logo_019](https://user-images.githubusercontent.com/38171859/89202526-14855000-d581-11ea-8276-8b065d5c4501.png)

Used Colors from Material Design Palette.
Designed in Inkscape.
No attribution necessary.

Inspired by the bookshelf icon you showed there: 

- I made the book corners more clearly rounded, while varying in sizes, following the similar positioning of two books standing tall and one leaning. 
 
- I made the colors bolder with **Indigo**, **Amber**, and **Pink** instead of the pale Blue, Yellow and Red. 
(Keep in mind, color can easily be adapted to a different palette, if you have one in mind.)
 
- Instead of a free hanging wall shelf, I created a **Rich Mocha** Bookshelf Frame, allowing for shaping and size association.

- In contrast to the circle that sets the icon from your example, the background for this is **Transparent**, and not a perfect geometric shape, to fit in with current design styles. (This can easily be changed.)
 
- The current size of this vector image file is 3500 by 3500 pixels. This can easily be manipulated larger or smaller.

**Please provide feedback.**

**Comment by knjk04** [comment]
Thanks, that's quite nice.

A couple of small suggestions:
- Could you make the amber book thinner? I think it would look better that way
- This is quite pedantic, but could you ensure that all books are touching the base of the shelf and there is no gap between the indigo book and the left bookshelf frame?

I especially like the darker colours used on the spine of the books!

**Comment by Onyx-Obelisk** [comment]
Thank you for your feedback and suggestions.
I have attempted your modifications.

![Book_Logo_020](https://user-images.githubusercontent.com/38171859/89428624-9bb1ff80-d70a-11ea-84b3-82e5e1ffc5b6.png)

Used Colors from Material Design Palette.
Designed in Inkscape.
No attribution necessary.

**Please provide feedback.**

**Comment by knjk04** [comment]
This is great, thanks so much!

**Comment by knjk04** [comment]
Would it be possible to send the logo as 1000x250 so that we can replace our existing banner?

**Comment by Onyx-Obelisk** [comment]
![Book_Banner_03](https://user-images.githubusercontent.com/38171859/89669933-52021a00-d8ae-11ea-8627-c358055f809c.png)

Used Colors from Material Design Palette.
Designed in Inkscape.
No attribution necessary.

**Please provide feedback.**

**Comment by knjk04** [comment]
Thanks a lot for this, it looks great. I especially like the rounded corners!
