### ISSUE TITLE
Reset fields when book is moved between shelves

### ISSUE THREAD

**Issue by Tom-private** [knjk04/book-project#271]
**When moving a book between shelves, shelf specific fields do not get reset**

A book in a specific predefined shelf should just have values for the fields that should technically be filled for a book being in the specific state the shelf suggests. We do not reset the affected fields which leads to illogical entries.

Example:
When a book is moved from the "Reading" shelf to the "To Read" shelf, the date_started_reading and date_finished_reading are not set to null.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the home page and click on "Add book"
2. Fill out the necessary fields, set Book shelf to "Read", enter values for date started and date finished
3. Click on "Add book"
4. Check book in database: data_started_reading, date_finished_reading have values
5. Select shelf "Read"
6. Click on the book you just created
7. Change shelf from "Read" to "To Read"
8. Click on "Update book"
9. Check book in database: data_started_reading, date_finished_reading still have values

**Expected behaviour**

When moving a book from the "Read" shelf to the "To Read" shelf, the dates should be set to null.
Same behaviour is expected for the other fields supplied in the additional context, so a field should be set to null, when a book is moved to a shelf where the field should have no value.

**Additional context**

The dates do only serve as an example here. 

More fields are affected. Following table should provide an overview:
(X: field can be present in this state of the book)
| Field               | To Read | Reading | Read | Did Not Finish |
|---------------------|---------|---------|------|----------------|
| pagesRead           |         |         |      | X              |
| dateStartedReading  |         | X       | X    | X              |
| dateFinishedReading |         |         | X    |                |
| bookReview          |         |         | X    |                |
| rating              |         |         | X    |                |

title, numberOfPages, genre, seriesPosition, edition, bookRecommendedBy, author, predefinedShelf, customShelf, tags can be present in all states.

**Comment by knjk04** [comment]
Thanks a lot for this, this is very thorough. Could you also add the `rating` and `bookReview` fields to the table (only applicable for `read` books)?

(To prevent the user from accidentally losing some data when moving a book to a different shelf, it's probably worth showing them a confirmation dialog informing them of data loss and asking them whether they're happy to proceed. I'll make a separate issue for that, though.)

**Comment by Tom-private** [comment]
Could rating and review not be also present in the did_not-Finish-state? So that the user can save, why they stopped reading and how bad the book was.

I would like to work on the issue, thank you for asking. :)
But I first have to finish the tests, I should manage to do that today, I hope.

**Comment by knjk04** [comment]
Short(er) answer:

You're right to bring up whether `rating` and `review` should also be present for `did not finish` books. This is a grey area. Currently, we do not permit that -- you have to finish a book before reviewing it. The reason for that is because it may be unfair for one to review a book that they did not finish. 

Long answer:

While it may not matter now if a user rates and/or leaves a review for a book they did not finish (after all, a user can only see the ratings of their own books, not that of others), I think it's best to remain with our current approach. As you may know, Goodreads suffers from the issue of fake/malicious reviews where a user rates a book they haven't actually read. If we ever allow for reviews to be accessible to the public (if a user is willing to share it), then it may be worth having some safeguards in place to check for fake reviews (e.g. asking questions<sup>1</sup> to ensure a user has actually read the book). In line with that, it doesn't seem fair to me to allow for reviews where a reader has not read the entire book because if they had, they may have actually liked it (and, of course, a user may not be able to answer those questions if they haven't read the book in its entirety).

Your suggestion was a good one. I have already considered it, but I'm open to changing my mind on this. If we do decide to not implement checks to ensure a user has read a book, we can always allow ratings & reviews for `did not finish` books. However, I think it's easier to start with the assumption that we are going to implement the checks. If we change course later, it'll be straightforward to change. That's not true for the other way around.

I appreciate this is a long answer to a short question, but hopefully that explains the reasoning behind the decision. If you disagree with any of this, let us know. 

> I would like to work on the issue, thank you for asking. :)
But I first have to finish the tests, I should manage to do that today, I hope.

Excellent. I'll assign you to the issue. 

1. This might be tough. We would need questions that are verifiable, but not questions where the answers are fact (e.g. 'What is the name of the protagonist?'). The questions would need to be opinionated (e.g. 'Why do you think the protagonist did X?'). We wouldn't want people to just search for the answer on a search engine (the questions would also need to change). We may decide not to implement this.

**Comment by Tom-private** [comment]
Based on you explanation I do understand, why the values should not be present there. Especially looking at the further development of the project, I fully agree to your reasoning.

**Comment by Tom-private** [comment]
I have an idea how to implement this:
- add a new method to the valueChangeListener of the predefinedShelfField
- the new method fills an array with the fields that should be null for the new state
- then, the method uses clearComponentFields() to set the value of the fields to null / empty

This way, the changes only get applied to the book, when the user hits save / update. So we can display him a warning beforehand.

**Problem with this solution:**
There is no field for review yet (see #171) so this approach does only work for pagesRead, the two dates and rating.
→maybe implement #171 first? or make a separate issue for the review, because atm it cannot be set anyways

**Comment by Tom-private** [comment]
Hi @knjk04 you said that you would assign me, can you do that? :)
And may I ask for your opinion regarding A and B or rather my idea in general?

**Comment by knjk04** [comment]
> Hi @knjk04 you said that you would assign me, can you do that? :)
Oops, I'll do that now.

>  And may I ask for your opinion regarding A and B or rather my idea in general?
Sure. Apologies, I missed this for some reason.

If I've understood correctly, your approach generally seems fine. I didn't understand why we need the array, though. What if `clearComponentFields()` (or some method that it calls) knows which fields need to be null instead?

Let's get the review merged in first. If you've already started on this, you can rebase once the review field PR has been merged in.

The tests seem good.

**Comment by Tom-private** [comment]
Thank you. :)

> I didn't understand why we need the array, though. What if clearComponentFields() (or some method that it calls) knows which fields need to be null instead?

In the array the fields that should be reset are stored to pass them to clearComponentFields. Like so:
```java
// in the valueChangeListener of the predefinedShelfField
case TO_READ:
    fieldsToReset = new HasValue[]{pagesRead, dateStartedReading, dateFinishedReading, rating};

// before a new save event is fired
ComponentUtil.clearComponentFields(fieldsToReset);
```
> Is this to test whether nulls are stored in the database?

yes.

Small update on the initial idea:
I implemented my idea and played around with changing between the shelves in the form. The method called in the valueChangeListener of the predefinedShelfField cannot call the clearComponentFields method like I described in my first comment. Instead, it should only fill the array.
The fields must be cleared only when the save event is called, using the array that was filled beforehand. This is no problem, just for your information. This leads to the array ```fieldsToReset``` having to be an attribute of the BookForm.

(If the fields would be cleared as soon as the shelf is changed, switching from e.g. Read -> ToRead -> Read would result in null-values for the dates, even if some values are present for the book, therefore the reset has to happen later.)

**Comment by knjk04** [comment]
> In the array the fields that should be reset are stored to pass them to clearComponentFields. 

That makes sense.

> (If the fields would be cleared as soon as the shelf is changed, switching from e.g. Read -> ToRead -> Read would result in null-values for the dates, even if some values are present for the book, therefore the reset has to happen later.)

That also makes sense.

Thanks for the update.
