### ISSUE TITLE
Check whether the form correctly updates fields

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#90]
Test whether the book form can correctly update a book's fields when the update button is pressed.

A `ParameterizedTest`, rather than a `Test`, may be needed.

Karibu testing should be used.

**Comment by Tom-private** [comment]
I am a bit unsure, on how to write the tests now.
I wrote tests for adding and deleting a book, these were no problem.
Now I am working on a parameterized test for updating a book, including moving a book between shelves, but what should I assert, when I move a book from Reading to To-Read? I would want to assert, that the startedReading-date should be null, that would be technically correct, I think, but the value is not overwritten, like you have already mentioned.

My idea would be now, to comment out the cases that are not working properly at the moment, with a comment that these should be commented in as soon as the bug is fixed.

Technically it is wrong to e.g. have a "To-Read" book with a finished reading date. I think, we should open an issue for that. I can take care of that if you agree to my perception.

**Comment by knjk04** [comment]
You're right, testing whether the values of the irrelevant fields (e.g. date started or date finished for a `to read` book) are reset when a book is moved to a different shelf should be a separate issue. It would be good to write that in a TDD style (the test should fail if we wrote it now).

Commenting out the failing tests sounds good to me. 

Could you create a new issue for testing and implementing the reset? (I could do it myself, but it would be good to double-check that we're on the same page in terms of the requirements for the issue).
